### ISSUE TITLE
The controls not support lambda slot

### ISSUE THREAD

**Issue by elct9620** [jonspalmer/view_component_storybook#104] opened 2021-11-11 08:45 UTC
When we create a slot use lambda

```ruby
class ExampleComponent < ViewComponent::Base
  renders_one :badge, lambda { |classes: ''|
    BadgeComponent.new(classes: ['example__badge', classes].join(' '))
  }
end
```

The story will unable to pass the validation

```ruby
class ExampleComponentStories < ViewComponent::Storybook::Stories
  story(:default) do
    constructor(
      # ...
    )
    badge(classes: text('example'))
  end
end
```

If use `badge(classes: 'example')` will work correctly. But I cannot find the reason why `param` is required In this case.

---

### Workaround

For each story 
```ruby
story(:default) do
  # ...

  # NOTE: Workaround to ensure lambda slot param is detected
  slots.map(&:slot_method_args).each { |args| args.resolve_method_args({}) }
end
```

**Comment by jonspalmer** [comment] 2022-01-16 22:03
I think this is fixed as part of #111 and that this is a dupe of #105. Please test and confirm.

**Closed** 2022-01-17 02:08 UTC
